# https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        "max-requests-inflight": "10000"
        "max-mutating-requests-inflight": "10000"